version: 2
jobs:
  build:
    
    working_directory: ~/circleci-demo-java-spring
    
    machine: true
  ruby:
    version: rbx-2.2.6

general:
   artifacts:
     - $CIRCLE_TEST_REPORTS
     - target
     
test:
  override:
    - mvn clean install
  post:
    - mkdir -p $CIRCLE_TEST_REPORTS/junit/
    - find . -type f -regex ".*/target/failsafe-reports/.*xml" -exec cp {} $CIRCLE_TEST_REPORTS/junit/ \;
